# Generated by Django 3.2.16 on 2023-02-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='prev_status',
            field=models.CharField(choices=[('pPending', 'Pending'), ('cCompleted', 'Completed'), ('eExpired', 'Expired'), ('aAborted', 'Aborted')], default=None, max_length=10, null=True),
        ),
    ]
